name: aimat
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - rdkit
  - pip:
      - bokeh==2.4.2
      - docker==5.0.3
      - ipywidgets==7.7.0
      - jupyter==1.0.0
      - jinja2==3.0.0 # cannot be imported by dependencies
      - jupyter-client==6.0.0 # breaks nbgrader
      - matplotlib==3.5.1
      - nbgrader==0.6.2
      - networkx==2.7.1
      - numpy==1.22.3
      - openpyxl==3.0.9
      - pandas==1.4.1
      - pygame==2.1.2
      - pymysql==1.0.2
      - pyvis==0.1.9
      - pyyaml==6.0
      - seaborn==0.11.2
      - scikit-learn==1.0.2
      - tables==3.7.0
      - tensorflow==2.8.0
      - torch==1.11.0
      - torchvision==0.12.0
      - torchaudio==0.11.0
      - xlrd==2.0.1
